### ISSUE TITLE
Status bar uses `quotes' instead of ‘quotes’

### ISSUE THREAD

**Issue by argv-minus-one** [neotron/EDPathFinder#12]
In the Route Viewer window, when selecting a settlement, the status bar shows a message like this:

    Copied system name `NLTT 53889' to the system clipboard.

Notice the use of U+0060 GRAVE ACCENT and U+0027 APOSTROPHE as quotation marks. This was somewhat common in decades past, but looks ugly in modern fonts. Please consider using U+2018 LEFT SINGLE QUOTATION MARK `‘` and U+2019 RIGHT SINGLE QUOTATION MARK `’` instead.

I'm using version 1.1.2.

Thanks for making this tool, by the way. ☺️ Wish I had it months ago!

**Comment by neotron** [comment]
Odd. I certainly didn't enter it that way intentionally. Weird editor "auto fixing" of my quotes perhaps.

**Comment by neotron** [comment]
Fixing in next release.
