### ISSUE TITLE
Show probability of getting specific data

### ISSUE THREAD

**Issue by argv-minus-one** [neotron/EDPathFinder#14]
In [the spreadsheet](https://docs.google.com/spreadsheets/d/1IVPYPqXbqC7pYY2UggEXLSO0CMaE0ksZMB2Ejlh0aYI/edit#gid=0), there are some statistics about how likely one is to receive a given data item from scanning a given settlement type. Please show this information, where available, in EDPathFinder.

**Comment by neotron** [comment]
Currently I only deal with the data as a "has it or not" but I've been wanting to show the data. It's kind of opaque exactly what it means though. It'd be nice to have it as a filter as well.

**Comment by neotron** [comment]
This is completed.
