### ISSUE TITLE
Unknow Origin System

### ISSUE THREAD

**Issue by RedokPaw** [neotron/EDPathFinder#21]
??? windows 10 64
![2017-07-21_14-20-19](https://user-images.githubusercontent.com/30343249/28462021-04ba3664-6e22-11e7-99be-644c2ffed01f.png)

**Comment by TPRDroid** [comment]
Windows 10 64bit. Out in Colonia get this error with TIR, COLONIA, KOJEARA as well.
![unknowncoloniasystem](https://user-images.githubusercontent.com/31322660/29684360-9e2339d4-8909-11e7-8612-6032a857f044.png)

**Comment by neotron** [comment]
This is related to another issue and are caused by issues not in EDDB.io. I think scanning the journals would suffice to find the systems when you're out in unexplored areas.

**Comment by neotron** [comment]
Journal is scanned for systems now so this should work fine for systems you've been to including your current system.
