### ISSUE TITLE
Manual Starting System coordinates

### ISSUE THREAD

**Issue by CMDR-Dess** [neotron/EDPathFinder#24]
Hello! That's a great tool you've made. Thanks a lot!
The only thing I'm missing is that I cannot enter my current coordinates manually. It's a pain in the ass to find the nearest system which is in the database to start creating an exploration route while I'm in the middle of nowhere. I mean, the origin system.
For example, spansh.co.uk tool has an option to find the nearest neutron star. It would be wonderful to have such feature in ED pathfinder.
Thanks.

**Comment by neotron** [comment]
I can understand why this would be useful. One possibility is to add systems from the journal files (or at least recent journal files). Manual entry too of course.

**Comment by neotron** [comment]
Current version now adds all systems found in the journals to the live-database, so this is effectively resolved.
