### ISSUE TITLE
The program freezes after scanning the game.

### ISSUE THREAD

**Issue by P4EJIA** [neotron/EDPathFinder#26]
![screenshot 2018-01-16 002](https://user-images.githubusercontent.com/32153947/34991349-462a8314-fb04-11e7-9f1f-a3ad31ca7736.jpg)

I5-3570k 8GB RAM
Win 10 Pro 1709
Build 16299.192
EDPathFinder: Release 1.4

Release 1.3 works without problems.

p.s. Can I help translating the program into Russian?

**Comment by P4EJIA** [comment]
Can I help translating the program into Russian?

**Comment by Nishi** [comment]
Tried recently, but never could use this program because of this never-ending bug.
btw I have Qt 5.10.0 installed.

**Comment by neotron** [comment]
I have no idea why this is happening sadly. Can you explain the steps taken to get here?

As for translations, haven't looked at that  at all yet so not an easy thing to do at the moment.

**Comment by neotron** [comment]
I wonder if it's a localization issue (like the journal having Russian text). I don't have any such journals to test with - if you don't mind @P4EJIA , could you zip up at least some of the journal files and email to neotron@gmail.com ?

Also @Nishi do you play with a non-English locale?

**Comment by Nishi** [comment]
@neotron I play using English locale (both OS & game), but I have non-default Russian locale installed in OS.

**Comment by Nishi** [comment]
It should be related to SSL, as the busy thread is running inside Qt SSL elliptic curve code.

2nd stacktrace:
```
0, ntoskrnl.exe!KeExpandKernelStackAndCalloutEx+0x25d3
1, ntoskrnl.exe!KiCheckForKernelApcDelivery+0x25
2, ntoskrnl.exe!IoCallDriver+0x6d63
3, ntoskrnl.exe!longjmp+0x4cca
4, ntdll.dll!memset+0x50
5, ntdll.dll!RtlWow64GetThreadSelectorEntry+0x53a
6, ntdll.dll!EtwEventWriteStartScenario+0x41d8
7, ntdll.dll!RtlValidateProcessHeaps+0x3f8
8, ntdll.dll!RtlValidateProcessHeaps+0x6c5
9, ntdll.dll!RtlQueryHeapInformation+0x3c
10, ntdll.dll!RtlQueryProcessHeapInformation+0x3ad
11, ntdll.dll!RtlQueryProcessDebugInformation+0x3af
12, kernel32.dll!Heap32Next+0x6a
13, libeay32.dll!RAND_poll+0x4f8
14, libeay32.dll!lh_node_usage_stats_bio+0x206
15, Qt5Network.dll!QSslEllipticCurve::shortName+0x2191
16, Qt5Network.dll!QSslEllipticCurve::shortName+0x20c9
17, Qt5Network.dll!QSslCertificate::QSslCertificate+0x79
18, Qt5Network.dll!QSslConfiguration::QSslConfiguration+0x199
19, Qt5Network.dll!QSslConfiguration::QSslConfiguration+0x1b
20, Qt5Network.dll!QNetworkReply::writeData+0x28b9
21, Qt5Network.dll!QNetworkReply::writeData+0x1e99
22, Qt5Network.dll!QNetworkAccessManager::createRequest+0x964
23, Qt5Network.dll!QNetworkAccessManager::head+0x1a
24, EDPathFinder.exe+0x4ac10
25, Qt5Core.dll!QThread::start+0x331
26, kernel32.dll!BaseThreadInitThunk+0xd
27, ntdll.dll!RtlUserThreadStart+0x1d

```
1st stacktrace (just when the program started)

```
0, ntoskrnl.exe!KeExpandKernelStackAndCalloutEx+0x25d3
1, ntoskrnl.exe!MmUnlockPages+0xd5d
2, ntoskrnl.exe!KeWaitForMutexObject+0x19f
3, ntoskrnl.exe!KeInitializeSemaphore+0x388
4, ntoskrnl.exe!KeExpandKernelStackAndCalloutEx+0x260d
5, ntoskrnl.exe!KiCpuId+0x24e6
6, ntdll.dll!RtlReportSqmEscalation+0x638
7, ntdll.dll!EtwEventWriteStartScenario+0x1d06
8, ntdll.dll!EtwEventWriteStartScenario+0x3d23
9, ntdll.dll!RtlValidateProcessHeaps+0x3f8
10, ntdll.dll!RtlValidateProcessHeaps+0x6c5
11, ntdll.dll!RtlQueryHeapInformation+0x3c
12, ntdll.dll!RtlQueryProcessHeapInformation+0x3ad
13, ntdll.dll!RtlQueryProcessDebugInformation+0x3af
14, kernel32.dll!Heap32Next+0x6a
15, libeay32.dll!RAND_poll+0x4f8
16, libeay32.dll!lh_node_usage_stats_bio+0x206
17, Qt5Network.dll!QSslEllipticCurve::shortName+0x2191
18, Qt5Network.dll!QSslEllipticCurve::shortName+0x20c9
19, Qt5Network.dll!QSslCertificate::QSslCertificate+0x79
20, Qt5Network.dll!QSslConfiguration::QSslConfiguration+0x199
21, Qt5Network.dll!QSslConfiguration::QSslConfiguration+0x1b
22, Qt5Network.dll!QNetworkReply::writeData+0x28b9
23, Qt5Network.dll!QNetworkReply::writeData+0x1e99
24, Qt5Network.dll!QNetworkAccessManager::createRequest+0x964
25, Qt5Network.dll!QNetworkAccessManager::head+0x1a
26, EDPathFinder.exe+0x4ac10
27, Qt5Core.dll!QThread::start+0x331
28, kernel32.dll!BaseThreadInitThunk+0xd
29, ntdll.dll!RtlUserThreadStart+0x1d

```

**Comment by neotron** [comment]
Thanks. This is kind of odd. I recently added OpenSSL libraries to the build, perhaps that'll change it. Very odd though, I guess related to doing a query to EDSM to get the coordinates for an unknown system.

**Comment by Niklan** [comment]
Agree. Downgrade to 1.3 solve the problem.
OS, Game, other stuff all on English.

**Comment by crowstwo** [comment]
Same here, downloaded 1.4 today and it froze.

**Comment by GlebYaltchik** [comment]
Same problem ((
1.4

**Comment by vetall812** [comment]
Same. Just installed 1.4 (haven't tried pathfinder yet), froze after initial scan and every other run.

Game, OS locale, default language on English. If it's correlate to another language in journal - it can be, as I play in multycrew with non-english player.

PS. 1.3 runs smooth

**Comment by BlackGoga** [comment]
Same problem 1.4

**Comment by Gimi1967** [comment]
I'm seeing the same issue with 1.4.
1.3 ran fine.
Running on Windows 10 pro. I am running it on a separate computer, but unfortunately I never get to the point where I can set the correct journal path.
My computer setup.
English Win 10 pro
Locale (keyboard, time etc) Norwegian
GUI interface and everything else is in English.
Of note, Norwegian uses comma (,) as the decimal separator. Not period.  This has been the cause of problems I have seen before.

**Comment by P4EJIA** [comment]
@neotron I sent my journals to the email.

**Comment by neotron** [comment]
I uploaded a new build, could you give it a shot? It solved the problem for another user (note this isn't really stable, I'm in the middle of trying to better support 4k displays).

**Comment by P4EJIA** [comment]
@neotron 
It seems everything works fine.
Scanning the logs was successful.
Routes are being built.
Thank you!
![screenshot 2018-02-13 005](https://user-images.githubusercontent.com/32153947/36148949-c1cad514-10f8-11e8-919a-0b67f01ef5e7.jpg)

**Comment by Nishi** [comment]
Works for me as well. Thank you!

**Comment by GlebYaltchik** [comment]
Nice! Now all works like a charm.
Thank you very much!
