### ISSUE TITLE
How do you know which planet to scan

### ISSUE THREAD

**Issue by Mrintrovert** [neotron/EDPathFinder#33]
Everything is amazing for plotting routes to scan planets - except I can't see how to know what planet to scan?

Other sites have information to show you which planet to go to to scan such as the road to riches index plotter.

I feel I could be missing something.

**Comment by neotron** [comment]
This currently isn't possible in the app, and considering the upcoming changes to exploration it'll actually no longer be needed (you don't fly to scan, and don't even know which planet is which until scanned anyway).

So won't fix it.

Note, until the patch you can use EDDiscovery for this:
![image](https://user-images.githubusercontent.com/20304/47628002-96b12c80-daf0-11e8-97bf-fc89c0707ef6.png)
