### ISSUE TITLE
System name instead of Settlement name

### ISSUE THREAD

**Issue by c0dejunKie** [neotron/EDPathFinder#5]
Not sure if this is a bug or if it is meant to be like this but I think that the System name should get copied to the clipboard instead of the Settlement name when you click on an item on the Route Viewer screen.  The reason for this is because I am not able to search for Settlement names from the galaxy map, so if the System name is copied to the clip board instead of the Settlement name then it would make things much easier to work with because some system names can be pretty extravagant and hard to remember and all you would have to remember is the settlement name once you have searched for the system on the map.

**Comment by neotron** [comment]
In the 1.1.1 release this is fixed (should be).

**Comment by neotron** [comment]
Fixed in 1.1.1
