### ISSUE TITLE
Please can we have a path finder option for finding Water Worlds, Earth Like Worlds.

### ISSUE THREAD

**Issue by BeckyYork** [neotron/EDPathFinder#8]
Now that the Exploration rewards are so good can we have a Pathfinder route plotting a course for Water Worlds, Earth Like Worlds and High Metal Content Worlds.

It'd be nice to have a filters for
- In the "Habital Zone"
- Around primary star
- Starting System

All the data can be from EDSM API; they have a body API coming soon.
It seems this would be a perfect extension to your application since you already have the algorithm to plot point-by-point path and exclude systems already scanned; the only difference being you can only scan the same planet one time ever.

**Comment by neotron** [comment]
[https://cdn.discordapp.com/attachments/125106523037761536/310999744270827522/5UxCZ.png](Soon...)

**Comment by neotron** [comment]
![5uxcz](https://cloud.githubusercontent.com/assets/20304/25791439/2eb35e4c-3375-11e7-89c2-e466daf5cf75.png)
Soon

**Comment by neotron** [comment]
1.3 is just released with this feature, both for circular routes, and one-way routes (the latter being a bit weird at times).
